### ISSUE TITLE
Authenticatoin fails if password contains special symbols

### ISSUE THREAD

**Issue by lostintime** [stefanprodan/mgob#104]
Hello and Thanks for this great tool,

Today I've tried mgob with a mongodb instance using `SCRAM-SHA-1` authentication and it was failing with: 

```
time="2020-03-04T14:31:57Z" level=error msg="On demand backup failed mongodump log 2020-03-04T14:31:57.910+0000\tFailed: can't create session: could not connect to server: connection() : auth error: sasl conversation error: unable to authenticate using mechanism \"SCRAM-SHA-1\": (AuthenticationFailed) Authentication failed. : exit status 1" plan=all
```

I figured out this to be caused by password containing some special symbols: `+-[>[`. `mongodump` from docker container was working properly using same password, probably passwod is not encoded in a proper way while passed from mgob to mongodump, after changing password to alpha only - it worked.

**Comment by cedricve** [comment]
Any idea to make this work? this is a bummer.

**Comment by lostintime** [comment]
> Any idea to make this work? this is a bummer.

I just used a "safe" password, and did not investigate further

**Comment by cedricve** [comment]
Just found out that by defining this option `params: "--authenticationDatabase admin"` it works as expected.

**Comment by atline** [comment]
> Just found out that by defining this option `params: "--authenticationDatabase admin"` it works as expected.

Works like a charm!
