### ISSUE TITLE
Error certificate rclone Mega

### ISSUE THREAD

**Issue by RafaMunoz** [stefanprodan/mgob#134]
Hello,

I try upload the backup to Mega with rclone but i received the next error when the aplication init the login:
``1620749431.gz to backmongo:my-backup-bucket failed 2021/05/11 16:10:52 Failed to create file system for \"backmongo:my-backup-bucket/backmongo-1620749431.gz\": couldn't login: Post \"https://g.api.mega.co.nz/cs?id=4195822075\": x509: certificate signed by unknown authority : exit status 1" plan=backmongo``

it seem and error with the CA install on the docker image. Could you check it out?

Thanks!

**Comment by wonko** [comment]
Hi,

verified on the latest mgob docker image and the CACerts do contain the right root certificate: 

```
bash-5.0# openssl x509 -in /etc/ssl/certs/ca-cert-USERTrust_RSA_Certification_Authority.pem -noout -fingerprint
SHA1 Fingerprint=2B:8F:1B:57:33:0D:BB:A2:D0:7A:6C:51:F7:0E:E9:0D:DA:B9:AD:8E
```

The sha1 fingerprint matches what I get by just navigating to `https://g.api.mega.co.nz/cs` and inspect the certificate in my browser. Configuring rclone and using it against mega (with a bogus login) also works (accesses the endpoint, but fails on the login, but accepts the certificate to use the API).
