### ISSUE TITLE
Mgob travis doesn't build any more

### ISSUE THREAD

**Issue by wonko** [stefanprodan/mgob#138]
...due to the unauthenticated pulling from Docker Hub. 

This prevents builds/tests to run, and no docker images are published.

See https://docs.docker.com/docker-hub/download-rate-limit/#how-do-i-authenticate-pull-requests for fixes.

**Comment by maxisam** [comment]
Not sure if you are still using it 
I created a gh action to deal with it in my fork. 

https://github.com/stefanprodan/mgob/commit/d5b61cfd00dcedbd8374ae020699880d69482b03
