### ISSUE TITLE
Allow to disable compression to help backups that allow for deduplication 

### ISSUE THREAD

**Issue by DavyLandman** [stefanprodan/mgob#146]
Currently the backups are all gziped, which makes perfect sense.

For our use case we are storing the backups on a share that gets daily backups (using [borgbackup](https://www.borgbackup.org/)). 

However, the deduplication (which works much like git's chunking algorithm) will not be able to recognize the 90% common parts between the backups, due to the fact that compression turns it into something close to entropy.

Are you open for a config option that disables the `--gzip` argument to `mongodump`?

**Comment by maxisam** [comment]
it is done here https://github.com/maxisam/mgob/commit/d8b69591ca2a75675ee3c3905bd0d3ffcb96611d
