### ISSUE TITLE
Proposal: Disable local disk retention when external storage is enabled

### ISSUE THREAD

**Issue by bweston92** [stefanprodan/mgob#15]
Looking at the README it says:

> For long term backup storage you could use a GCP Bucket since is a cheaper option than keeping all 
backups on disk.

https://github.com/stefanprodan/mgob/commit/ccad92c6fba0372452c7ce84e7fd2024e1f92c03#diff-e42e703f8eacc6c0bc4465761e4cdc1bR252

Yet we still make a 3gb disk, do we still need it?
https://github.com/stefanprodan/mgob/blob/master/k8s/mgob-gstore-dep.yaml#L65

**Comment by stefanprodan** [comment]
You should keep the latest back on the `mongo-storage` disk for fast recovery. Setting the retention to 1 does just that. All your older backups will be stored in GCP Bucket but the last one will also be stored locally. You could decrease the disk size if your backup is less than 3GB.

**Comment by stefanprodan** [comment]
Maybe it would be useful for mgob to support zero local retention, this way you would not have to attache the `mongo-storage` disk and use only on the bucket storage.

**Comment by leothesen** [comment]
@stefanprodan we have a security concern when it comes to retaining data locally with mgob. To be able to specify a retention of 0, when using another backup method such as S3 would be a huge help.
