### ISSUE TITLE
Status of the last backup?

### ISSUE THREAD

**Issue by bodsch** [stefanprodan/mgob#150]
Would it be possible to output the status of the last backup via the metrics interface?
This could be used to trigger an alarm if the backup did not work.

**Comment by maxisam** [comment]
I use increase(mgob_scheduler_backup_total{job="mongodb-backup-mgob", plan="db"}[<backup interval>])
In this way the value should be always >=1 if it works

**Comment by bodsch** [comment]
Thank you for your advice.
I will test it in the near future.

**Comment by maxisam** [comment]
Just found another solution. 

use this datasource https://github.com/yesoreyeram/grafana-infinity-datasource, you can query /status endpoint and get the data
