### ISSUE TITLE
Project Maintenance 

### ISSUE THREAD

**Issue by maxisam** [stefanprodan/mgob#161]
First of all, thanks for the amazing project. 
I wonder if you are interested in having another admin for this project or if you have time to take care some PRs. 
Currently I have made some changes on my fork for my needs. I will happy to contribute them back if you like,  but I will have to take time to break them into smaller PRs for different features. So I would like to know if you want it first before I spending time to do it.

Here are the features I made so far. (I tested all of them, since I am using it and I will write unit test code as much as I could)

- Add Github Actions for build and deployment #138 
- Change Email library to handle certificate issue #160 
- mask password in logger
- add retry policy
- some updates for libraries
- backup validation #23 (Work in progress)

I totally understand maintaining an OSS project is a chore. Not sure how long I will keep working on this either : ) But I am happy to contribute my code if you want, but no pressure. I am fine to keep it in my fork.

**Comment by stefanprodan** [comment]
@maxisam I have no bandwidth to maintain mgob, I'm going to archive the project and link to your fork if that's Ok with you.

**Comment by maxisam** [comment]
Totally fine and understandable. I have so many projects I should probably archive as well haha. Thank you for this awesome project!
