### ISSUE TITLE
Store backup plans in a remote storage

### ISSUE THREAD

**Issue by bweston92** [stefanprodan/mgob#19]
I want to be able to run this application in a Swarm environment and configure using a remote storage API.
Something like Etcd or just from grabbing the plans from a S3 bucket.

**Comment by stefanprodan** [comment]
You could use Docker Swarm configs and provision those from S3. Loading the configs from a remote storage has lots of challenges. Mgob loads the backup plans only at startup, if you add a new config in S3 the only way to make Mgob aware of the new config is to restart the service.
