### ISSUE TITLE
backup using s3 with k8s

### ISSUE THREAD

**Issue by tvernick** [stefanprodan/mgob#20]
Hey there,
I'm wondering if s3 will work with k8s here. I have existing dbs outside of k8s and want to leverage the backup function here if that's possible.

**Comment by stefanprodan** [comment]
If the dbs are not reachable from within k8s you can deploy mgob as standalone container on a VM in the dbs VPC and run the backups from there.

**Comment by tvernick** [comment]
Right so I'm basically trying to setup this container in kubernetes with s3 as well but I'm not certain what is required for the containers spec. I have s3 defined in a ConfigMap similar to the way you have GCP.
