### ISSUE TITLE
tmp Storage cleanup

### ISSUE THREAD

**Issue by tvernick** [stefanprodan/mgob#21]
Hi Stephan,
I see backups staying on the container in /storage after they are transferred to an s3 store. Are those suppose to be cleaned up after they are transferred? Or are they cleaned up with the retention policy set? Will they get cleaned up on s3 and the container?

**Comment by stefanprodan** [comment]
The retention setting is for the local storage only. You should set that to 1. As for S3 it’s up to you to implement retention, mgob doesn’t delete anything from remote storage.

**Comment by tvernick** [comment]
Ok thanks
