### ISSUE TITLE
auth for /storage

### ISSUE THREAD

**Issue by gassibern** [stefanprodan/mgob#22]
It would probably be a cool feature to have the possibility to protect the content in /storage - path only for authorized access.

In the actual situation, everybody with access to the webserver can get all the dumped data. Is there any solution for this?

Thanks
Martin

**Comment by stefanprodan** [comment]
On Kubernetes you can use an ingress controller with basic-auth in front of mogb and make the mgob service as ClusterIP

**Comment by bsormagec** [comment]
what can i do on docker-swarm or traefik @stefanprodan ?

**Comment by franklouwers** [comment]
Note that using ingress with basic auth doesn't prevent direct pod-to-pod access. So if you don't trust all your pods, there's no protection you can implement.
