### ISSUE TITLE
Backup does not work at all due to moving log file error

### ISSUE THREAD

**Issue by guytish** [stefanprodan/mgob#28]
When you run the mongodump command with --gzip and --archive options there is no output to stdout.
In logToFile function you're creating the file only if data length > 0.
Later, you're trying to move this log file (which not created) and it fails. 

err = sh.Command("mv", log, planDir).Run()
if err != nil {
	return res, errors.Wrapf(err, "moving file from %v to %v failed", log, planDir)
}

**Comment by kvascz** [comment]
This issue disappeared when I removed the `database:` key for the configmap.

**Comment by marcelinhov2** [comment]
Hi, I'm with this error and idk what I need to do. Can anyone help me pls? 🙏

**Comment by guytish** [comment]
@marcelinhov2 - as @kvascz wrote, did you try to remove the database:?

**Comment by marcelinhov2** [comment]
Hey @guytish the problem was that my databases are not created. Shame on me!!!

**Comment by chris-scentregroup** [comment]
I also get this as well.

```
INFO[0016] Backup started                                plan=config
mv: can't rename '/tmp/config-1557464760.log': No such file or directory
ERRO[0019] Backup failed moving file from /tmp/config-1557464760.log to /storage/config failed: exit status 1  plan=config
```

**Comment by chris-scentregroup** [comment]
Check https://github.com/stefanprodan/mgob/pull/76 - let me know if I didn't cover your use case. Its possible I didn't cater for code in other parts.

**Comment by chris-scentregroup** [comment]
https://github.com/stefanprodan/mgob/pull/76/files#diff-c1200ceabb9994d8786d2389fae289c1R54
