### ISSUE TITLE
/bin/sh: mongodump: command not found

### ISSUE THREAD

**Issue by BigBuckBunny** [stefanprodan/mgob#30]
Hi,
I'm at a complete loss with the following error message:
"mongodump failed /bin/sh: mongodump: command not found : exit status 127" 

I have the community edition https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.6.4.tgz running on webfaction and have compiled mgob to run on a different port but no dump.

mongodump  works on it's own, do I need a script, would you have an example/solution.

I got the concussion thingy and at a total loss

Thanks

**Comment by stefanprodan** [comment]
You can change the mgob port using this flag https://github.com/stefanprodan/mgob/blob/master/main.go#L23

Are you running mgob in a container?

**Comment by BigBuckBunny** [comment]
Can't use container's with Webfaction, is this my prob I need to run it in a container. I reviewed your page at three this morning couldn't sleep.
