### ISSUE TITLE
Error while backup routine

### ISSUE THREAD

**Issue by marcelinhov2** [stefanprodan/mgob#35]
Hi guys, I already deployed mgob at my Kubernetes Cluster and it was working fine. 

But now, I'm getting this error and I don't know how to handle this:
```
{"error":"mongodump log 2018-06-29T21:53:31.016+0000\twriting googlecrawler.reviews to archive '/tmp/googlecrawler-1530309210.gz' 2018-06-29T21:53:31.017+0000\twriting googlecrawler.processes to archive '/tmp/googlecrawler-1530309210.gz' 2018-06-29T21:53:31.017+0000\twriting googlecrawler.credentials to archive '/tmp/googlecrawler-1530309210.gz' 2018-06-29T21:53:31.017+0000\twriting googlecrawler._properties to archive '/tmp/googlecrawler-1530309210.gz' 2018-06-29T21:53:31.023+0000\tFailed: archive writer: error writing data for collection `googlecrawler.credentials` to disk: error reading collection: Failed to parse: { find: \"credentials\", skip: 0, snapshot: true, $readPreference: { mode: \"secondaryPreferred\" }, $db: \"googlecrawler\" }. Unrecognized field 'snapshot'. / Mux ending but selectCases still open 3 : exit status 1"}
```

Does anyone already went through this?

**Comment by marcelinhov2** [comment]
It's mongo version guys. It's not working with Mongo 4.0. I downgraded it to 3.6 and it worked like a charm.

**Comment by okanmilli** [comment]
Same issue for me

**Comment by marcelinhov2** [comment]
@okanmilli check your mongodb version

**Comment by marcelinhov2** [comment]
Hello, I'm getting a new error:

```mc config host for plan google failed: exit status 1```

It's in s3.go file.

**Comment by marcelinhov2** [comment]
anyone?

**Comment by jscottsf** [comment]
Just spent an hour setting this up. LOVE it. Doesn't work tho, Mongo 4.0. Bummed.

**Comment by stefanprodan** [comment]
There is no MongoDB 4.0 support, it says very clearly in the readme. When mongo 4.0 package will ship for alpine/stable I will make a new release.
