### ISSUE TITLE
Rely on kubernetes scheduler

### ISSUE THREAD

**Issue by pjanuario** [stefanprodan/mgob#38]
When you are doing backups from a database with considerable sizes we need to tune the limits of the deployment, using a statefulset means we need to have this running permanently and requesting a lot of resources from the cluster.

Ideally if we could rely on the kubernetes cronjobs and have successfull exit code we would prevent long running executions of this process and triggered them on scheduled time only.

Any considerations on this? Is this doable with start flags?

**Comment by stefanprodan** [comment]
This would need a total rewrite of mgob as mgob has it's own http server, local db for state, internal jobs, metrics etc. I don't have the time for such a transformation.
