### ISSUE TITLE
Question:  Mongo Sharded Cluster Support

### ISSUE THREAD

**Issue by ambrons** [stefanprodan/mgob#4]
This looks killer and full featured.  Taking a quick glance at the readme I saw the yaml config file only supports on database.

Everything I read about doing backups of a sharded cluster talks about turning off the balancer, fsyncLocking read replica in each shard and doing a dump of config, and each shard.  Then reversing those steps once done.

Is your application intended to backup a mongo sharded cluster via mongos, have support for the suggested steps for by MongoDB, or have no support for sharded clusters?

In either case great work!

**Comment by stefanprodan** [comment]
I use it for sharded clusters by pointing mgob to a mongos instance like stated here https://docs.mongodb.com/v3.0/tutorial/backup-small-sharded-cluster-with-mongodump/

I didn't test it on huge clusters, I can't tell if the fsyncLocking is required or not.

**Comment by ambrons** [comment]
Thanks for the quick reply @stefanprodan .   Yeah that was my question to.  We are in the process of going from a mongo replica to a sharded cluster as we need a lot more write capability based on our applications needs.

Looked like making the switch was jumping in to the deep end of the pool over our previous backup strategy.   Did you setup your cluster yourself with a config replica server as well as shard replicas and mongos (routers)?

We're currently using docker swarm so my plan is to install your service in our swarm and give it a shot with our staging setup.

One last question I noticed you defined a few volumes.  What do you loose between runs if the volumes aren't present?  Meaning how stateful is this service if the backups themselves are stored in S3?

**Comment by stefanprodan** [comment]
I wrote a bootstraper in go to spin a Mongo sharded cluster on Docker Swarm, here is the project https://github.com/stefanprodan/mongo-swarm

The volumes are used for:

* storing the backup before it gets uploaded to S3
* storing the dump logs 
* storing backup jobs status

If the volumes get deleted you will lose the local backups and logs so you will have to download a backup file from S3 to restore a db, that’s about it.
