### ISSUE TITLE
Releases after 0.8 breaking S3 integration

### ISSUE THREAD

**Issue by marcelinhov2** [stefanprodan/mgob#41]
Hi, after a few weeks of pain I decided to find out what was happening with my backup routine. I was using the ```edge``` image at my cluster and all my backups was breaking with the error:

```mc config host for plan google failed: exit status 1```

I tried a few times to solve the problem but the only way was to downgrade to the version ```0.8```. After that, everything is working great again.

**Comment by stefanprodan** [comment]
Something must have changed in the Minio CLI, looks like GCP is on the old API version `S3v2` and AWS S3 and Minio are on `S3v4`

**Comment by stefanprodan** [comment]
What are you using in mgob config, it's `S3` or `gcloud` ?

**Comment by marcelinhov2** [comment]
S3

**Comment by marcelinhov2** [comment]
I tried to use Gcloud, but I had permissions issues.

**Comment by marcelinhov2** [comment]
For S3 i was using S3v4 already. It's not working, for sure.

**Comment by stefanprodan** [comment]
This what I've just said, Gcloud is not compatible with S3v4. please check my commit

**Comment by marcelinhov2** [comment]
I understood about the Gcloud API but I left this and focused in AWS S3 integration. That's what I'm trying to explain, it is not working using the ```S3v4``` and it was working before. Someday I woke up and it was not working anymore, in production, without change anything.

Just worked when I downgraded to ```0.8```.

**Comment by stefanprodan** [comment]
Ah I got confused by the fact that you named the plan google. 

Can you try to run `mc config host add s3  https://s3.amazonaws.com <Access Key> <Secret Key> S3v4` with your AWS S3 bucket and see if you get any error out of it?

**Comment by stefanprodan** [comment]
You can exec into the mgob container or install mc on your machine from [here](https://docs.minio.io/docs/minio-client-complete-guide)

**Comment by stefanprodan** [comment]
@marcelinhov2 can you please try the latest `edge` release, it should fix the S3 problem.

**Comment by marcelinhov2** [comment]
Tried and it's working @stefanprodan.

Thanks.
