### ISSUE TITLE
Proposal: Azure blob storage

### ISSUE THREAD

**Issue by etoriet** [stefanprodan/mgob#45]
Hi,

This is cool solution. I want to use this but I use Azure which is not supported by mgob.
Can I add some code to support Azure blob storage?

**Comment by stefanprodan** [comment]
Hi @etoriet 

It would be great if you can add Azure support. You could follow the gcloud bucket implementation, I think it should be similar.

**Comment by etoriet** [comment]
Thank you for prompt response. I'll try to add Azure support!
