### ISSUE TITLE
MongoDB 4.0 build

### ISSUE THREAD

**Issue by andrelillvede** [stefanprodan/mgob#47]
Hi!
Do you have any plans on making a build for mongo 4.0?

I would also like to take the opportunity to thank you for all the work you put on this image, It has saved me from a lot of headaches. 🙃

/André

**Comment by kladiv** [comment]
+1

**Comment by stefanprodan** [comment]
The mongo-tools package v4 hasn't been released yet https://pkgs.alpinelinux.org/packages?name=mongodb-tools&branch=v3.8&arch=x86_64

**Comment by kladiv** [comment]
Hello, by now you can create a custom Dockerfile:

```
FROM stefanprodan/mgob
# update mongo to 4.0 using edge repository
RUN echo "@edge http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories && \
    echo "@edge http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories && \
    apk add --no-cache boost-system@edge mongodb@edge mongodb-tools@edge
```

Then you will have following packages inside the container:
```
~ # apk list |grep mongo
mongodb-tools-4.0.0-r0 x86_64 {mongodb-tools} (Apache) [installed]
mongodb-tools-3.6.4-r0 x86_64 {mongodb-tools} (Apache)
php7-mongodb-1.4.4-r0 x86_64 {php7-mongodb} (PHP)
php7-mongodb-1.5.2-r0 x86_64 {php7-mongodb} (PHP)
mongodb-4.0.1-r0 x86_64 {mongodb} (AGPL3) [installed]
mongodb-3.6.7-r0 x86_64 {mongodb} (AGPL3)
```
```
~ # mongod --version
db version v4.0.1
git version: 54f1582fc6eb01de4d4c42f26fc133e623f065fb
OpenSSL version: LibreSSL 2.7.4
allocator: system
modules: none
build environment:
    distarch: x86_64
    target_arch: x86_64
```
```
~ # mongodump --version
mongodump version: v3.8.0-804-g416df12a01
git version: 416df12a0154a8d8202dc6dad8a3e0d9310875a0
Go version: go1.10.3
   os: linux
   arch: amd64
   compiler: gc
OpenSSL version: LibreSSL 2.7.4
```

**Comment by stefanprodan** [comment]
There is no need for that, I can use the `edge` tag. My concern is about stability

**Comment by stefanprodan** [comment]
@andrelillvede  @kladiv I've released `stefanprodan/mgob:edge` with mongo-tools v4 can you please try it out and let me know if it works on your setup. 

Thanks

**Comment by kladiv** [comment]
@stefanprodan Seems ok
Is it normal *mongod* package is not present anymore?

**Comment by stefanprodan** [comment]
the docker image never had the mongod package only mongo-tools

**Comment by andrelillvede** [comment]
Sorry for the late reply.
I can confirm it works on my setup!

**Comment by stefanprodan** [comment]
thanks
