### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by skarj** [stefanprodan/mgob#49]
Is there a way to set a password through an environment variable (from the Kubernetes secret) to avoid storing in the repository? Thanks for this great tool!

**Comment by skarj** [comment]
Implemented using init container and sed.

**Comment by vishnoisuresh** [comment]
Hi @skarj  would it be possible for you to share your implementation using init container ?

**Comment by skarj** [comment]
@vishnoisuresh please see here https://github.com/skarj/helm-mgob/blob/master/templates/mgob-statefulset.yaml#L23-L43

**Comment by vishnoisuresh** [comment]
@skarj  Thanks :) I am wondering what could be reason behind to use **statefulset** instead of using just **deployment**?

**Comment by stefanprodan** [comment]
@vishnoisuresh the deployment spec doesn't support volume claim templates and you will probably need that if you want the local backups volume being automatically provisioned.
