### ISSUE TITLE
The access key ID you provided does not exist in our records

### ISSUE THREAD

**Issue by luisalguien** [stefanprodan/mgob#50]
I'm trying to use the credentials of a IAM user I created on the AWS console, but when the backup is tried to be done, it throws the "The access key ID you provided does not exist in our records" error, even though my user from which I'm taking the credentials has full access to S3. Anyone happened to have the same issue?

**Comment by JustDoItSascha** [comment]
you have to use https://s3.amazonaws.com as url. The example settings are using the demo minio server. I have no idea why and it's very confusing.

**Comment by easybi-at** [comment]
yes, if you are changing configuration, changes are not reflected unless you delete mgob.db and /root/.mc in container and then restarting container, helps....
