### ISSUE TITLE
mc: \u003cERROR\u003e Failed to copy

### ISSUE THREAD

**Issue by sonaikar** [stefanprodan/mgob#52]
mc command failed to run copy to S3 storage. 

**Below error is observed.** 
Object name cannot be empty mc: \u003cERROR\u003e Session safely terminated. To resume session `mc session resume bWEhwoRn` : exit status 1"

Looks like "mc" command is not appending target with object name to copy. 

mc command should be, 
_**mc cp /storage/project/db.gz  s3/projectname/db.gz**_

Existing command is. 
_**mc cp /storage/project/db.gz  s3/bucketname/**_

Due to missing target object name the command is failing to copy object into S3 bucket.

**Comment by sonaikar** [comment]
Is there any quick solution to this issue? Thanks!

**Comment by stefanprodan** [comment]
The integration tests are using a Minio server and I don't see this error. I'm guessing this is AWS specific

**Comment by Paic** [comment]
Problem is present in version 0.10.
Is this fixed in master (stefanprodan/mgob:edge) or does this need a PR ?
