### ISSUE TITLE
Mongo 4 tools release date

### ISSUE THREAD

**Issue by Juanchimienti** [stefanprodan/mgob#59]
Hello there,

I'm trying the tool and so far it looks awesome. We are using mongo 4 and setup the mgob edge image and it looks fine. I would like to avoid living the "edge" version so the questions are: 
When do you plan to make the next release?
Are you planning to include the mongo 4 tools?
Can we help in any way to make that happen?

**Comment by stefanprodan** [comment]
Hi @Juanchimienti I've updated the mongo tools to v4.0.5 and I've published `stefanprodan/mgob:1.0` to Docker Hub.
