### ISSUE TITLE
stefanprodan/mgob:latest is not working

### ISSUE THREAD

**Issue by jbdhacf** [stefanprodan/mgob#67]
Hi,

I´ve started mgob with my config. And in my /status the scheduler is wrong. I used a schedule of every minute for testing 0 * * ? * * *

Also i have plan1.yaml and plan2.yaml it can´t find neither. /status/plan1 etc

Just wondering if i missed something or if it´s broken at the moment?
my mongodb is running 3.6.4 ...is stefanprodan/mgob:latest not compatible with this image?
i understood it as they were backwards compatible

**Comment by skbly7** [comment]
Can you try with `* * * * *` instead for every minute testing?

**Comment by jbdhacf** [comment]
I changed to another cron expression and got it working

First i used: https://www.freeformatter.com/cron-expression-generator-quartz.html
Maybe they support "non standard" cron expressions... I don´t know.

Changed to: https://crontab.guru 
To create another expression. It worked

Sorry for creating an issue over this!
