### ISSUE TITLE
Feature request: helm chart

### ISSUE THREAD

**Issue by dimhoLt** [stefanprodan/mgob#7]
Kubernetes has an official package manager, Helm, for which creating charts is really simple. If we could implement this, installation of this package on Kubernetes would be as simple as `$ helm install stable/mgob`.

Setting up Helm is done through `$ helm create --client-only`.

More information can be found [here](https://github.com/kubernetes/helm/blob/master/docs/charts.md).

**Comment by dimhoLt** [comment]
I've implemented mgob as a chart for my own needs. If there's interest for it, I can create a pull request with the basic functionality implemented.

**Comment by stefanprodan** [comment]
Hi @dimhoLt yes please do. Have you used StatefulSets like [here](https://github.com/stefanprodan/mgob/tree/master/k8s) ?

**Comment by dimhoLt** [comment]
Yes, I used the k8s from that directory in the charts :) Note though that I just implemented the basic functionality. Will provide a PR when I have some time!

**Comment by dimhoLt** [comment]
Oh, I'm sorry. I completely forgot about this. I'll make sure to create a PR ASAP. Sorry for the delay.
