### ISSUE TITLE
Azure blob storage not working

### ISSUE THREAD

**Issue by iMartyn** [stefanprodan/mgob#83]
Azure backup is not working because the azure provider shells out to az cli and az is not in `stefanprodan/mgob`.

Worse still, there is no error issued, the file just never ends on the blob storage.

The choice of go-sh is an interesting one, I'm sure it was picked because of timeout, however go-sh calls sh, so calling sh from go-sh is one layer of potential problems.

I haven't worked with this module before but somewhere it is swallowing the error (sh will give a `127` error code if the command doesn't exist).

We are lucky we caught this because someone other than the person who set up the backup required a restore, so it seemed easier to go get it from blob than the local pod.  Luckily they just needed a backup not a backup from a few days ago.

**Comment by iMartyn** [comment]
@etoriet could you weigh in on the choice of go-sh?  Perhaps there's a neater way to solve the timeout so go's native exec which should be a bit more reliable can be used?

**Comment by patrickmslatteryvt** [comment]
It works fine for me on Azure Blob storage, can you give some details of your config perhaps?

**Comment by esin** [comment]
Hi
Can approve @iMartyn 
How can I enable debug log for output?
Thank you

**Comment by etoriet** [comment]
Hi @iMartyn ,

Would you check your docker image is sufficiently new? Azure support starts at 1.0 release and if your image is before 1.0, configuration about azure may be silently ignored.
