### ISSUE TITLE
Select collection for a backup

### ISSUE THREAD

**Issue by underlow** [stefanprodan/mgob#89]
In my db I have several relatively big collections which are generated from others and I don't want to backup them. Would be great to have an option to select collections to backup.

**Comment by rebrendov** [comment]
You can do `params: "--excludeCollection=<collection_name>"` in the target config of a backup plan. Under the hood mgob uses mongodump so you can use flags from [here](https://docs.mongodb.com/manual/reference/program/mongodump/) to set it up to your liking.
