### ISSUE TITLE
S3 bucket does not exist

### ISSUE THREAD

**Issue by jbdhacf** [stefanprodan/mgob#94]
```
Backup failed S3 uploading /storage/plan/plan-1574075580.gz to plan/XXX-XXX/ failed `/storage/plan/plan-1574075580.gz` -> `plan/XXX-XXX/plan-1574075580.gz` mc: <ERROR> Failed to copy `/storage/plan/plan-1574075580.gz`. Bucket `XXX-XXX` does not exist. Total: 203.34 KB, Transferred: 0 B, Speed: 0 B/s : exit status 1" plan=plan
```

Is there an issue with '-' in the bucket name XXX-XXX?

The backup is created fine, but S3 upload wont work.

Thank you

**Comment by jbdhacf** [comment]
'-' doesn´t seem to be the issue

**Comment by 5sdba** [comment]
time="2020-06-30T11:20:07+08:00" level=error msg="Backup failed S3 uploading /storage/mongo1/mongo1-1593487200.gz to mongo1/mongo-bakcup failed `/storage/mongo1/mongo1-1593487200.gz` -> `mongo1/mongo-bakcup/mongo1-1593487200.gz` mc: <ERROR> Failed to copy `/storage/mongo1/mongo1-1593487200.gz`. The ap-east-1 location constraint is incompatible for the region specific endpoint this request was sent to. Total: 0 B, Transferred: 1.66 KiB, Speed: 810 B/s : exit status 1" plan=mongo1
time="2020-06-30T11:20:07+08:00" level=info msg="Next run at 2020-06-30 11:22:00 +0800 CST" plan=mongo1

**Comment by 5sdba** [comment]
time="2020-06-30T12:10:03+08:00" level=info msg="new dump" archive=/tmp/mongo1-1593490200.gz err="<nil>" mlog=/tmp/mongo1-1593490200.log planDir=/storage/mongo1
time="2020-06-30T12:10:04+08:00" level=error msg="Backup failed S3 uploading /storage/mongo1/mongo1-1593490200.gz to mongo1/mongo-bakcup/mongo/ failed `/storage/mongo1/mongo1-1593490200.gz` -> `mongo1/mongo-bakcup/mongo/mongo1-1593490200.gz` mc: <ERROR> Failed to copy `/storage/mongo1/mongo1-1593490200.gz`. Bucket `mongo-bakcup` does not exist. Total: 0 B, Transferred: 0 B, Speed: 0 B/s : exit status 1" plan=mongo1
