### ISSUE TITLE
Email notifier failing with EOF error

### ISSUE THREAD

**Issue by BlackTurtle123** [stefanprodan/mgob#96]
Hello!
The email notifier is failing with below error:

`time="2020-01-16T14:57:00Z" level=error msg="Notifier failed sending email notification failed: EOF"`

**Comment by AminSojoudi** [comment]
same here

**Comment by AminSojoudi** [comment]
Managed to solve it by using a domain name for mail server address instead of IP address.

**Comment by BlackTurtle123** [comment]
I was using a domainname

**Comment by obeyda** [comment]
i had the same issue, fixed it with using port 587 (TLS)
